"""add collections tables

Revision ID: 8a62f0ce45d1
Revises: 
Create Date: 2026-07-10 12:08:30.775271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a62f0ce45d1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collection_movies', schema=None) as batch_op:
        batch_op.alter_column('movie_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.create_unique_constraint('uq_collection_movie', ['collection_id', 'movie_id'])

    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visibility', sa.Enum('public', 'private', name='visibility'), nullable=False, server_default='private'))
        batch_op.add_column(sa.Column('cover_image_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('cover_image_url')
        batch_op.drop_column('visibility')

    with op.batch_alter_table('collection_movies', schema=None) as batch_op:
        batch_op.drop_constraint('uq_collection_movie', type_='unique')
        batch_op.alter_column('movie_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
